# Generated by Django 5.2.4 on 2025-07-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='note <built-in function id>')),
                ('note', models.TextField(verbose_name='write your note here.')),
            ],
        ),
    ]
