# Generated by Django 5.2.4 on 2025-07-19 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
