# Generated by Django 5.2.4 on 2025-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Book_app', '0002_note_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
