# Generated by Django 5.2.4 on 2025-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Book_app', '0003_alter_note_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
