# Generated by Django 5.2.4 on 2025-08-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Book_app', '0004_note_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Updated_at',
        ),
    ]
