# Generated by Django 5.2.4 on 2025-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Book_app', '0005_remove_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
