# Generated by Django 5.2.4 on 2025-08-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Book_app', '0007_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
